M48
; DRILL file {KiCad 9.0.0} date 2025-03-07T19:53:28+0900
; FORMAT={-:-/ absolute / inch / decimal}
; #@! TF.CreationDate,2025-03-07T19:53:28+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
INCH
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.0256
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C0.0866
%
G90
G05
T1
X6.9604Y-2.6539
X6.9604Y-2.8815
T2
X6.5197Y-2.6614
M30
