M48
; DRILL file {KiCad 9.0.0} date 2025-03-07T19:36:36+0900
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-07T19:36:36+09:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C2.200
%
G90
G05
T1
X176.795Y-67.41
X176.795Y-73.19
T2
X165.6Y-67.6
M30
